# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

        #doorbird:
        #devices:
        #- host: 10.0.0.210
        #username: ghbunl0001
        #password: ddJ7bpzvUp
        #token: 4aeab727cb45d6d60e004f30c66a7b35
        #hass_url_override: 10.0.0.248:8123

homeassistant:
  allowlist_external_dirs:
    - /tmp

# Example configuration.yaml entry for Google Mail.
notify:
  - name: "DOORBIRD"
    platform: smtp
    server: "smtp.gmail.com"
    port: 587
    timeout: 15
    sender: "as87321234@gmail.com"
    encryption: starttls
    username: "as87321234@gmail.com"
    password: "zjoywhmhlpkkwuke"
    recipient:
      - "sb87321234@gmail.com"
      - "as87321234@gmail.com"
    sender_name: "DOORBIRD"

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml

# Example configuration.yaml entry
logger:
  default: info
  logs:
    pyalarmdotcomajax.pyalarmdotcomajax: debug

frontend:
  # your configuration.
  themes: !include_dir_merge_named themes

sonoff:
  username: as87321234@gmail.com
  password: Qaws1234!
  mode: cloud
  reload: always  # update device list every time HA starts

