- id: '1637541769240'
  name: Throughout the night
  entities:
    light.corner:
      supported_color_modes:
      - brightness
      friendly_name: Corner
      supported_features: 41
      state: 'off'
    light.piano:
      supported_color_modes:
      - brightness
      friendly_name: Piano
      supported_features: 41
      state: 'off'
- id: '1639777920132'
  name: Dim Living Room
  entities:
    light.corner:
      supported_color_modes:
      - brightness
      color_mode: brightness
      brightness: 48
      friendly_name: Corner
      supported_features: 41
      state: 'on'
    light.piano:
      supported_color_modes:
      - brightness
      color_mode: brightness
      brightness: 38
      friendly_name: Piano
      supported_features: 41
      state: 'on'
