- platform: systemmonitor
  resources:
     - type: disk_use_percent
       arg: /
     - type: memory_free
     - type: memory_use
     - type: processor_use

- platform: template
  sensors:
     outdoor_humidity:
        friendly_name: "Outdoor Humidity"
        entity_id: weather.weatherapi_home
        unit_of_measurement: '%'
        value_template: "{{ state_attr('weather.weatherapi_home', 'humidity') }}"
     outdoor_temperature:
        friendly_name: "Outdoor Temperature"
        entity_id: weather.weatherapi_home
        unit_of_measurement: '°C'
        value_template: "{{ state_attr('weather.weatherapi_home', 'temperature') }}"
     outdoor_wind:
        friendly_name: "Wind"
        entity_id: weather.weatherapi_home
        unit_of_measurement: 'km'
        value_template: "{{ state_attr('weather.weatherapi_home', 'wind_speed') }}"
     outdoor_pressure:
        friendly_name: "Pressure"
        entity_id: weather.weatherapi_home
        unit_of_measurement: 'p'
        value_template: "{{ state_attr('weather.weatherapi_home', 'pressure') }}"
     outdoor_windspeed_km:
        friendly_name: "Wind Speed (km)"
        entity_id: sensor.openweathermap_wind_speed_km
        unit_of_measurement: 'km'
        value_template: "{{ (float(states('sensor.openweathermap_wind_speed')) * 3.6 ) }}"

        #- platform: command_line
        #name: "bin alarmdotcom"
        #command: "python3 /config/bin/alarmdotcom.py"
        #scan_interval: 60
        #command_timeout: 60

- platform: command_line
  name: "bin collections gatineau"
  command: "python3 ./bin/collection_gat.py"
  scan_interval: 28800
  command_timeout: 60

- platform: template
  sensors:
    collection_gatineau_blue_bin:
      device_class: timestamp
      value_template: '{{ (states("sensor.bin_collections_gatineau")|from_json())["recyclage"] }}'
      unique_id: "collection_gatineau_recyclage"

    collection_gatineau_brown_bin:
      device_class: timestamp
      value_template: '{{ (states("sensor.bin_collections_gatineau")|from_json())["compostage"] }}'
      unique_id: "collection_gatineau_compostage"

    collection_gatineau_gray_bin:
      device_class: timestamp
      value_template: '{{ (states("sensor.bin_collections_gatineau")|from_json())["ordures"] }}'
      unique_id: "collection_gatineau_ordures"

    collection_gatineau_tree_bin:
      device_class: timestamp
      value_template: '{{ (states("sensor.bin_collections_gatineau")|from_json())["arbresnoel"] }}'
      unique_id: "collection_gatineau_arbresnoel"

      #collection_gatineau_bulky_waste:
      #device_class: timestamp
      #value_template: '{{ (states("sensor.bin_collections_gatineau")|from_json())["Bulky-waste"] }}'
      #unique_id: "collection_gatineau_bulky_waste"

      #collection_gatineau_bulky_wood_metal_waste:
      #device_class: timestamp
      #value_template: '{{ (states("sensor.bin_collections_gatineau")|from_json())["Bulky wood and metal articles"] }}'
      #unique_id: "collection_gatineau_bulky_wood_metal_waste"

